version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: tire_detection_mqtt
    ports:
      - "127.0.0.1:1883:1883"
    volumes:
      - ./infrastructure/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tire_detection_backend
    environment:
      - DATABASE_URL=sqlite:///./tire_detection.db
      - SECRET_KEY=laptop-dev-secret
      - ENVIRONMENT=development
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

  edge-device:
    build:
      context: ./edge
      dockerfile: Dockerfile
    container_name: tire_detection_edge
    environment:
      - DEVICE_ID=laptop_edge_001
      - MQTT_BROKER_HOST=mqtt
      - MODEL_SIZE=yolov8n
      - INFERENCE_DEVICE=cpu
    depends_on:
      - mqtt
      - backend
    volumes:
      - ./edge/test_images:/app/test_images:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: tire_detection_dashboard
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "127.0.0.1:8501:8501"
    depends_on:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

networks:
  default:
    driver: bridge
